name: Deploy English to Railway

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Add these as repository secrets in GitHub (see step 2)
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug Railway auth (temporary)
        run: |
          echo "=== railway version ==="
          railway --version || true
          echo "=== railway whoami (verifies token) ==="
          railway whoami || echo "railway whoami failed (token/auth issue)"

      - name: Deploy English service to Railway
        run: |
          set -e
          SERVICE_NAME="soundmirror-en"
          MODEL_ID="facebook/wav2vec2-large-xlsr-53-english"
          LANGUAGE="en"

          if [ -n "$RAILWAY_PROJECT_ID" ]; then
            echo "Deploying to project id: $RAILWAY_PROJECT_ID service: $SERVICE_NAME"
            railway up --service "$SERVICE_NAME" --detach --project-id "$RAILWAY_PROJECT_ID"
            railway variables set MODEL_ID="$MODEL_ID" LANGUAGE="$LANGUAGE" --service "$SERVICE_NAME" --project-id "$RAILWAY_PROJECT_ID"
          else
            echo "Deploying without explicit project id (ensure RAILWAY_TOKEN targets the right project)"
            railway up --service "$SERVICE_NAME" --detach || railway up --detach
            railway variables set MODEL_ID="$MODEL_ID" LANGUAGE="$LANGUAGE" --service "$SERVICE_NAME"
          fi
